version: "3.6"

services:
 minetest:
  image: registry.gitlab.com/minetest/minetest/server:5.5.0
  user: root
  volumes:
    - "minetest_home:/root/.minetest"
  ports:
    - "30000:30000/udp"

 admin:
  image: golang:1.18.0
  environment:
   WORLD_DIR: /minetest_home/worlds/world
  volumes:
   - "minetest_home:/minetest_home"
   - "./:/app"
   - "go_cache:/root/.cache"
   - "go_dir:/root/go"
  working_dir: /app
  command: ["sh", "-c", "go run ."]
  

volumes:
  minetest_home: {}
  go_cache: {}
  go_dir: {}