version: "3.6"

services:
 minetest:
  image: registry.gitlab.com/minetest/minetest/server:5.5.0
  user: root
  volumes:
    - "minetest_home:/root/.minetest"
    - "../mtadmin_mod:/root/.minetest/worlds/world/worldmods/mtadmin_mod"
    - "./minetest.conf:/etc/minetest/minetest.conf"
  ports:
    - "30000:30000/udp"

 admin_webapp:
  image: node:16.15.0-alpine3.15
  volumes:
   - "./:/app"
  working_dir: /app/public
  command: ["npm", "ci"]

 admin:
  image: golang:1.18.0
  environment:
   WORLD_DIR: "/minetest_home/worlds/world"
   WEBDEV: "true"
   APIKEY: "mykey"
  ports:
    - 8080:8080
  volumes:
   - "minetest_home:/minetest_home"
   - "./:/app"
   - "go_cache:/root/.cache"
   - "go_dir:/root/go"
  working_dir: /app
  command: ["go", "run", "."]
  

volumes:
  minetest_home: {}
  go_cache: {}
  go_dir: {}